apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thriftx-backend-monitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: thriftx-backend
  endpoints:
    - port: http-metrics
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
